### ISSUE TITLE
Zerocoin amount taken as a value instead of "amount_formatted"

### ISSUE THREAD

**Issue by seanPhill** [steel97/veil-explorer#1] opened 2022-01-17 14:59 UTC
Spotted by eRz- in Discord. The total zerocoin value has eight more zeroes before the decimal place. ;)

![Screen Shot 2022-01-17 at 9 57 13 am](https://user-images.githubusercontent.com/46495592/149792356-ba6dee9f-583a-4e18-9d51-fb29d26074f4.png)

Ah, in `getblockchaininfo` unlike for each denom, there is no "amount_formatted" number for "denom": "total", so it would be necessary simply to divide by 100000000.

**Comment by steel97** [comment] 2022-01-17 15:15
Thanks for report! Didn't notice that bug, It's probably caused by recent changes I made to fix typescript issues https://github.com/steel97/veil-explorer/commit/4455c7e04849acebd4bc50beb973f2fc300120cf. Fixed in https://github.com/steel97/veil-explorer/commit/f816db78a823dbd75141c895d61c99f48871a7df

**Closed as completed by steel97** 2022-01-17 15:15 UTC
